### ISSUE TITLE
Use SERVER_ADDR in login.php

### ISSUE THREAD

**Issue by omercnet** [tomgs/fb-page-aggregator#2]
Use `$_SERVER['HTTP_ADDR']` to dynamically find the url of the login page in https://github.com/tomgs/fb-page-aggregator/blob/master/login.php#L23 or just just `/` to get current location

**Comment by TomGranot** [comment]
It's actually $_SERVER['SERVER_ADDR'] as per [here](http://php.net/manual/en/reserved.variables.server.php), but I think they better input the full path or they'll get problems through the FB API. Leaving like this and closing for now
